name: CI - API Tests (Java)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17, 21]

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Dar permissão ao mvnw
        run: chmod +x mvnw

      - name: Rodar testes com Maven
        run: ./mvnw test
